### ISSUE TITLE
Architecture: Find a Storybook like for Astro

### ISSUE THREAD

**Issue by yoannfleurydev** [Fork-It-Community/forkit.community#107]

**Comment by JeanneGrenet** [comment]
It seems that the official documentation tool for astro is [Starlight](https://starlight.astro.build/) if it can help you

**Comment by yoannfleurydev** [comment]
> It seems that the official documentation tool for astro is [Starlight](https://starlight.astro.build/) if it can help you

Starlight is based on Astro, it is a Docusaurus or Nextra like. It maybe "too much" for what we want.

**Comment by yoannfleurydev** [comment]
We will create a "stories" collection that will have as many mdx as we have components to document them and generate a static documentation for component.

**Comment by yoannfleurydev** [comment]
@JeanneGrenet you can check my commit https://github.com/Fork-It-Community/forkit.community/commit/b4d6efa676be9ed0d0b98a224553d0a9955efe5a to see how we will do that

**Comment by marekbrze** [comment]
Found this project https://github.com/ocavue/astrobook

**Comment by yoannfleurydev** [comment]
> Found this project [ocavue/astrobook](https://github.com/ocavue/astrobook)

Oh nice, thank you, will definitely take a look! 👀
