### ISSUE TITLE
Sponsors area conception

### ISSUE THREAD

**Issue by JeanneGrenet** [Fork-It-Community/forkit.community#5]
## Description / Why?
The goal is to display the sponsors of an event according to its "rank". You also have to be able to manage the fact that the company can sponsor certain events, but not all of them.

## Links / Resources
Mock-up: 
![image](https://github.com/Fork-It-Community/forkit.community/assets/77801791/d39f8591-e660-4ea7-b025-1488a0197a47)

## Current status / Investigations

For now only the BearStudio sponsor is created and the image is missing. I think the best option to manage the data is to have an array containing the names of the sponsors of the event.

## How?
* [x]  Add array to event schema
* [x]  Add sponsorship "rank" to sponsor schema
* [x]  Use the tailwind UI component and adapt it to the Fork IT colors! 
* [ ]  A map on the array with names is required to display sponsor info in the corresponding file
* [x]  Create other sponsors files 

## Related issues:
* [x]  If sponsorship rank changes based on events?
* [x]  Display based on sponsorship rank?

**Comment by yoannfleurydev** [comment]
> Add array to event schema

What for? What is its name?

> Add sponsorship "rank" to sponsor schema

What about the fact that BearStudio is Silver on the Rouen event and Gold for the Hanoi event? This does not cover this use case.

**Comment by JeanneGrenet** [comment]
The solution could be to have one array per rank on the event with the corresponding sponsors names inside : 
`silverSponsors = ["bearstudio","anothersponsor"]`
With this we can sort the sponsors by rank to display them and change the rank based on events

Question : There is no gold sponsors on the sponsorship prospectus, it's just for Rouen or it could have gold sponsors on other events ?

**Comment by yoannfleurydev** [comment]
> The solution could be to have one array per rank on the event with the corresponding sponsors names inside :
silverSponsors = ["bearstudio","anothersponsor"]

I think we will have an issue with the `zod` schema. Can you please provide a bit of zod code so we make sure it is possible? A TypeScript playground is greatly appreciated. (You can use `import` in  https://www.typescriptlang.org/play, it will auto install the dependency).

**Comment by JeanneGrenet** [comment]
I did the zod schema and I had some comments [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGEIA2BqAxjMBFnAL5zpQQhwBEMAnmKsgLQjIAezANwAoUJFiI4ALxp0GTZtIjJhIkSUoBneJqKly2uAF5EIuHC2QsW6AC4UGbHkLEyFLAAoE5i3UJoUA7MVtrQzAA0vhZaJAAWqCAAhg7SAHQQAEYAVgbe0X5YSSCoqWk6UNgA5p4AlFF+fqBJVaUyBY0ZOXk+jX2WUCRlFdV1Df1+SQQwwzCVWDX1HX7UtcsWGWCGRQRjy6gAbqhYMFplSVBQSWye6SMLdbWb21NjcAD07wAqccBacH84FgIPAcCRUFotBc2HBUPxwVsuAD0HAAO6oNFJE5wGAQFB-MAEa5wKYEHEJSzWWxQJG2EDohI0-xQWFJeKUsJQAqrcY83yHY4zRyYHD4fTuSj5RroAKoIIsAUnSIFWIJZJlLK5MhSvpFEqzeaLcaNZBJGBtdKm811Z4eV5LfoECAkM0eA2jJ4QLZ23YOvpw8FQLbuh6e72Ue3GprJVqpdZwLpamA6iYDIYycpzD1R-pTIV3LOhnMrNap20R33FkjoMAa7rapBxGnoEOLNIAVygvpoYZeleW5BIAGtUKc60nvHAmxhWzbO93VuWdnt+mAGFYDO2zu0y5qelPm7OnvO3uQYMQj0v7T341f+6v25kCH8EsgypkIIRUFibV6+yu+kyBgsGkVAAGUqWgf5zkua5bkzQ1f3DZdal7H0AMaLRgAII4oAgzloIzC4rhuAtELQitHjvDC-CqAJ8JsKC4Bgkj4PuNs-3Q1DqPqD53jgAB1DEXSoZACSJGFKAIGEYApK4sCHf50UxbFKHJDFFXgMAWlQdRGj5Cw+VoJJ-k0GwYFEIA)

**Comment by yoannfleurydev** [comment]
[Something like this](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGEIA2BqAxjMBFnAL5zpQQhwBEMAnmKsgLQjIAezANwAoUJFiI4ALxp0GTZtIjJhIkSUoBneJqKly2uAF5EIuHC2QsW6AC4UGbHkLEyFLAAoE5i3UJoUA7MVtrQzAA0vhZaJAAWqCAAhg7SAHQQAEYAVgbe0X5YSSCoqWk6UNgA5p4AlFF+fqBJVaUyBY0ZOXk+jX2WUCRlFdV1Df1+SQQwwzCVWDX1HX7UtcsWGWCGRQRjBavjB76oAG6oWDOOmDj4+u6U+Y3oAahBLKfnMJEFsQnJZVlcmRHn0iiVZvNFuNGsgkjA2ulYfC6pttlM9v0CBASHCPBDRrVUR50Ut+qh+CRXlt8QsURAtsTdqS+s1Wql1nAukCYCCJgMhjJynMCdCJlNLukRrTmf1VhyiZQSaKLCR0GAAd1gUg4lAMDTFmkAK5QJk0Qn0tFM5VwcgkADWqBgWg13O8cB1esFUoNxtNqwVOwxfTADCsBkNzvafK5PXduvQ+pRvrGNuAMGIifNDMVfrW0YtjKDjTAhsyBGAWgSyDKmQghFQSS8WctRb8AHo23AACoJODQQJ99A23sOthaK7OcfYOAAdziwHifagA5gveIZwI45nwCIcEyqBQFbABCSbC4yw7cAAqlpqsOK3BRxFZwecVQ0NcD6uD+vUJuX7OjYwGkcAAKJpFUIGNnAHwXHAb7ukkZx7gwWDSKgz63gQZxQM+VQBBenaNsgcCNhA35QH2ODwdBcRIQeACMABMAAcz5MQArAAbM+HHMc+DEAAxMQALEucDZIaWAULhMH8JwlQlBcXCYecMlpMsoQ2NA1QADIfJuZRJFAUCnp4krCtKMp+FpthQOORkmWZ6SAj0HJaAQhpVJmz6XgAPNww4Hh5XmDkFljWHZHK-gQmZwP5gXfnAMVhbZOkLMsqzNoWSz7MyRy0Ek46aDYMCiEAA) will be more flexible in my opinion
