### ISSUE TITLE
Speaker Component

### ISSUE THREAD

**Issue by yoannfleurydev** [Fork-It-Community/forkit.community#8]
Create a component to show speakers and their information.

**Comment by JeanneGrenet** [comment]
# Conception 
## Scheme : 
Here is a proposal for the speaker scheme : [playground TS](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGEIA2BqAxjMBFnAL5zpQQhwBEMAnmKsgLQjIAezANwAoUJFiI4ALxp0GTZtIjJhIkSUoBneJqKly2uAF5EIuHC2cAhgGtUUAFwoM2PIWJkKWABQJzFnSEaE4sVqh2DswANAEWWiQAFqgg1s7SAHQQAEYAVgZ+cYFY1iCo6Rk6UNgA5j4AlLGBgaDWNagAqlAEFVW1DU3NlgCueQa9MNVYdfVZYIYlBANFFrk5E1MzcwvWS40rlhAkwLta6QcWGdZQUNZsPheBmTn5ZIVDH3DsnBWoWMMgHwAbWYgmiLAI2HsyGwzAAuvtPkNElAMBt+rNht1lkiLNREZ96o9tt5djjAvjBpSRLRrFo4JosDpREA)
## Display : 
Do we keep the mockup ?
![image](https://github.com/Fork-It-Community/forkit.community/assets/77801791/8b43591c-a053-4ff3-b95a-c38eaff3915b)

**Comment by yoannfleurydev** [comment]
> # Conception
> ## Scheme :
> Here is a proposal for the speaker scheme : [playground TS](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGEIA2BqAxjMBFnAL5zpQQhwBEMAnmKsgLQjIAezANwAoUJFiI4ALxp0GTZtIjJhIkSUoBneJqKly2uAF5EIuHC2cAhgGtUUAFwoM2PIWJkKWABQJzFnSEaE4sVqh2DswANAEWWiQAFqgg1s7SAHQQAEYAVgZ+cYFY1iCo6Rk6UNgA5j4AlLGBgaDWNagAqlAEFVW1DU3NlgCueQa9MNVYdfVZYIYlBANFFrk5E1MzcwvWS40rlhAkwLta6QcWGdZQUNZsPheBmTn5ZIVDH3DsnBWoWMMgHwAbWYgmiLAI2HsyGwzAAuvtPkNElAMBt+rNht1lkiLNREZ96o9tt5djjAvjBpSRLRrFo4JosDpREA)


For the schema, I think the "subject" elsewhere. Not sure where yet, but what if a speaker has multiple subject, and what if a speaker gives a talk in Rouen, but also in Hanoï. We have a many to many situation here.

Also, for the mockup, we can ask Dorian to do a design first.

**Comment by JeanneGrenet** [comment]
## Scheme
For the speaker scheme I think we can do that : [playground TS](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGEIA2BqAxjMBFnAL5zpQQhwBEMAnmKsgLQjIAezANwAoUJFiI4ALxp0GTZtIjJhIkSUoBneJqKly2uAF5EIuHC2cAhgGtUUAFwoM2PIWJkKWABQJzFnSEaE4sVqh2DswANAEWWiQAFqgg1s7SAHQQAEYAVgZ+cYFY1iCo6Rk6UNgA5j4AlLGBgaDWNagAqlAEFVW1DU3NcLk5vTDVWHX1WWCGJQQDRfEQJMDWBFrpS4EZ1lBQ1mw+282ZOflkhUPXcOycFahYAK4gPgDazILRLATY9sjYGIsbA6NoHEDMAC6jROQ0SUAwYwmUwyT26ixugWoMMx9VhMzm6wxWJxNBhtGsWjgmiwOlEQA)

And I think we have to do like the sponsors : put the speakers name in the event mdx to keep all the speakers and only display the good ones on the event. 

## Mockups : 
Like you said, we take that with Fork it! branding : 
![image](https://github.com/Fork-It-Community/forkit.community/assets/77801791/39d6d950-c44b-4423-8409-d9d5baa2bbaf)

**Comment by yoannfleurydev** [comment]
Go for it! 😄  @JeanneGrenet
